CREATE TABLE users (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    role VARCHAR(50) NOT NULL,
    created_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (login, first_name, last_name, email, role)
VALUES
    ('ebndrnk', 'Egor', 'Bondarenko', 'ebndrnk@gmail.com', 'admin'),
    ('petr_petrov', 'Petr', 'Petrov', 'petr.petrov@example.com', 'coordinator'),
    ('anna_sidorova', 'Anna', 'Sidorova', 'anna.sidorova@example.com', 'doctor'),
    ('olga_yo', 'Olga', 'Smirnova', 'olga.smirnova@example.com', 'nurse'),
    ('dimon', 'Dmitry', 'Dmitriev', 'dmitry.dmitriev@example.com', 'admin');

